import { AppCategory, AppData, JobData, StatData } from './types';
import { Smartphone, Code2, Download, Trophy } from 'lucide-react';

export const HERO_CONTENT = {
  name: "Cong Le",
  title: "Principal iOS Engineer @ Capital One",
  subtitle: "11+ years in iOS. Enterprise banking by day, indie apps by night. Gravitating towards the positive.",
  blurb: "",
  signalSentence: "",
  strengths: [] as string[],
  profileImage: "https://github.com/CongL3.png",
  email: "support@cong-le.com",
  appStoreLink: "https://apps.apple.com/gb/developer/cong-le/id954373766",
  githubLink: "https://github.com/CongL3",
  linkedinLink: "https://www.linkedin.com/in/cong-le-ios/",
  xLink: "https://x.com/CongLe",
};

export const STATS: StatData[] = [
  { label: "Experience", value: "11+ Years", icon: Code2, description: "iOS Engineering" },
  { label: "Apps", value: "40+", icon: Smartphone, description: "Live on App Store" },
  { label: "Downloads", value: "500k+", icon: Download, description: "Portfolio-wide" },
  { label: "Flagship", value: "250k+", icon: Trophy, description: "Anniversary Tracker" },
];

export const EXPERIENCE: JobData[] = [
  {
    id: "capone-principal",
    role: "Principal iOS Engineer",
    company: "Capital One",
    location: "Nottingham, UK",
    period: "Dec 2021 - Present",
    isCurrent: true,
    description: [
      "Leading architecture modernization across a large iOS codebase.",
      "Driving delivery across product, design, and QA in a regulated environment.",
      "Raising engineering quality through testing, CI/CD, and team standards.",
      "Mentoring engineers and shaping technical direction for long-term scalability."
    ],
    technologies: ["Swift", "SwiftUI", "UIKit", "Architecture", "CI/CD"]
  },
  {
    id: "career-break",
    role: "Career Break",
    company: "Teaching & Personal Development",
    period: "2019 - 2021",
    description: [
      "Focused on communication, mentoring, and leadership in education settings.",
      "Strengthened coaching and people skills now applied to engineering leadership."
    ],
    technologies: ["Communication", "Leadership", "Coaching"]
  },
  {
    id: "capone-senior",
    role: "Senior iOS Engineer",
    company: "Capital One",
    location: "London, UK",
    period: "2015 - 2018",
    description: [
      "Built and shipped core banking features used by large customer cohorts.",
      "Partnered across disciplines to maintain reliability and release quality."
    ],
    technologies: ["Objective-C", "Swift", "Jenkins", "TDD"]
  }
];

export const APPS: AppData[] = [
  {
    id: "anniversary",
    name: "Anniversary Tracker",
    category: AppCategory.UTILITIES,
    description: "The flagship relationship tracker for anniversaries, countdowns, and meaningful milestones.",
    downloads: "250k+",
    rating: 4.7,
    iconColor: "bg-rose-500",
    iconUrl: "/images/apps/1570714816/icon.jpg",
    isFeatured: true,
    url: "https://apps.apple.com/gb/app/anniversary-tracker/id1570714816?ct=congle-web-home&mt=8",
    landingPage: "/apps/anniversary-tracker/",
    screenshots: [
      "/images/apps/1570714816/screenshot-1.jpg",
      "/images/apps/1570714816/screenshot-2.jpg",
      "/images/apps/1570714816/screenshot-3.jpg",
      "/images/apps/1570714816/screenshot-4.jpg",
    ],
  },
  {
    id: "frankly-ai",
    name: "Frankly AI: Uncensored Chat",
    category: AppCategory.UTILITIES,
    description: "Chat with AI — frank, uncensored, 100% on your device.",
    iconColor: "bg-blue-500",
    iconUrl: "/images/apps/6766366146/icon.jpg",
    url: "https://apps.apple.com/gb/app/frankly-ai-uncensored-chat/id6766366146?ct=congle-web-home&mt=8",
    landingPage: "/apps/frankly-ai/",
  },
  {
    id: "couple-days",
    name: "Couple days counter",
    category: AppCategory.LIFESTYLE,
    description: "Track relationship milestones and day counts.",
    iconColor: "bg-rose-400",
    iconUrl: "/images/apps/1634973558/icon.jpg",
    url: "https://apps.apple.com/gb/app/couple-days-counter/id1634973558?ct=congle-web-home&mt=8",
    screenshots: [
      "/images/apps/1634973558/screenshot-1.jpg",
      "/images/apps/1634973558/screenshot-2.jpg",
      "/images/apps/1634973558/screenshot-3.jpg",
      "/images/apps/1634973558/screenshot-4.jpg",
      "/images/apps/1634973558/screenshot-5.jpg",
    ],
  },
  {
    id: "ollama-connect",
    name: "Ollama Connect",
    category: AppCategory.UTILITIES,
    description: "A private chat client for Ollama on iPhone.",
    iconColor: "bg-blue-500",
    iconUrl: "/images/apps/6769891596/icon.jpg",
    url: "https://apps.apple.com/gb/app/ollama-connect/id6769891596?ct=congle-web-home&mt=8",
    landingPage: "/apps/ollama-connect/",
  },
  {
    id: "football-career-quest",
    name: "Football Career Quest",
    category: AppCategory.ENTERTAINMENT,
    description: "Build a full football career from first prospect to club legend.",
    iconColor: "bg-purple-500",
    iconUrl: "/images/apps/6777125671/icon.jpg",
    url: "https://apps.apple.com/gb/app/football-career-quest/id6777125671?ct=congle-web-home&mt=8",
  },
  {
    id: "baby-screen-lock",
    name: "Baby Screen Lock: Kid Safe",
    category: AppCategory.ENTERTAINMENT,
    description: "Keep your little one entertained with age-appropriate activities while the screen stays locked.",
    iconColor: "bg-purple-500",
    iconUrl: "/images/apps/6761378897/icon.jpg",
    url: "https://apps.apple.com/gb/app/baby-screen-lock-kid-safe/id6761378897?ct=congle-web-home&mt=8",
    landingPage: "/apps/baby-screen-lock/",
  },
  {
    id: "hoop-quest",
    name: "Hoop Quest: Basketball Sim",
    category: AppCategory.ENTERTAINMENT,
    description: "Build a basketball career from backyard prospect to pro league legend.",
    iconColor: "bg-purple-500",
    iconUrl: "/images/apps/6775279715/icon.jpg",
    url: "https://apps.apple.com/gb/app/hoop-quest-basketball-sim/id6775279715?ct=congle-web-home&mt=8",
    landingPage: "/apps/hoop-quest/",
  },
  {
    id: "lovepet",
    name: "LovePet: Pookie & Couple App",
    category: AppCategory.LIFESTYLE,
    description: "Stay connected with your partner through shared virtual pets, mood tracking, and daily love notes.",
    iconColor: "bg-rose-400",
    iconUrl: "/images/apps/6761291886/icon.jpg",
    url: "https://apps.apple.com/gb/app/lovepet-pookie-couple-app/id6761291886?ct=congle-web-home&mt=8",
  },
  {
    id: "privatechat-ai",
    name: "PrivateChat AI: Ollama & LLM",
    category: AppCategory.ENTERTAINMENT,
    description: "Chat with AI — 100% private, 100% on your device.",
    iconColor: "bg-purple-500",
    iconUrl: "/images/apps/6761863969/icon.jpg",
    url: "https://apps.apple.com/gb/app/privatechat-ai-ollama-llm/id6761863969?ct=congle-web-home&mt=8",
  },
  {
    id: "kids-timer",
    name: "Kids Timer - Visual Countdown",
    category: AppCategory.PRODUCTIVITY,
    description: "Visual routine timers designed to help kids stay focused and independent.",
    iconColor: "bg-blue-500",
    iconUrl: "/images/apps/6747147301/icon.jpg",
    url: "https://apps.apple.com/gb/app/kids-timer-visual-countdown/id6747147301?ct=congle-web-home&mt=8",
    landingPage: "/apps/kids-timer/",
  },
  {
    id: "solunar",
    name: "Solunar: Best Fishing Times",
    category: AppCategory.UTILITIES,
    description: "Predict major and minor feeding periods with proven solunar theory for the best fishing times.",
    iconColor: "bg-blue-500",
    iconUrl: "/images/apps/6760960543/icon.jpg",
    url: "https://apps.apple.com/gb/app/solunar-best-fishing-times/id6760960543?ct=congle-web-home&mt=8",
    landingPage: "/apps/solunar-fishing/",
  },
  {
    id: "jump-rope-timer",
    name: "Jump Rope Timer & Tracker",
    category: AppCategory.LIFESTYLE,
    description: "A clean interval timer and workout log built for skipping and jump rope training.",
    iconColor: "bg-rose-400",
    iconUrl: "/images/apps/6771269878/icon.jpg",
    url: "https://apps.apple.com/gb/app/jump-rope-timer-tracker/id6771269878?ct=congle-web-home&mt=8",
  },
  {
    id: "link-saver",
    name: "Link Saver - fast and easy",
    category: AppCategory.UTILITIES,
    description: "Lightweight link manager to quickly save and organize useful URLs.",
    iconColor: "bg-emerald-500",
    iconUrl: "/images/apps/6743759106/icon.jpg",
    url: "https://apps.apple.com/gb/app/link-saver-fast-and-easy/id6743759106?ct=congle-web-home&mt=8",
  },
  {
    id: "life-countdown",
    name: "Life Countdown: Age Calculator",
    category: AppCategory.UTILITIES,
    description: "See your life in weeks and know exactly how much time you have left.",
    iconColor: "bg-blue-500",
    iconUrl: "/images/apps/6761100038/icon.jpg",
    url: "https://apps.apple.com/gb/app/life-countdown-age-calculator/id6761100038?ct=congle-web-home&mt=8",
  },
  {
    id: "simple-timer",
    name: "Simple Timer & Stopwatch Clock",
    category: AppCategory.PRODUCTIVITY,
    description: "Simple timer and stopwatch utility.",
    iconColor: "bg-blue-400",
    iconUrl: "/images/apps/6737737475/icon.jpg",
    url: "https://apps.apple.com/gb/app/simple-timer-stopwatch-clock/id6737737475?ct=congle-web-home&mt=8",
  },
  {
    id: "golden-hour",
    name: "Golden Hour: Light Planner",
    category: AppCategory.PHOTO_VIDEO,
    description: "Know exactly when the light gets good — every golden hour and light window a photographer needs.",
    iconColor: "bg-indigo-500",
    iconUrl: "/images/apps/6760960439/icon.jpg",
    url: "https://apps.apple.com/gb/app/golden-hour-light-planner/id6760960439?ct=congle-web-home&mt=8",
  },
  {
    id: "captions",
    name: "Captions: Auto Video Subtitles",
    category: AppCategory.PHOTO_VIDEO,
    description: "Auto-transcribe your videos into subtitles in 30 seconds, not 30 minutes.",
    iconColor: "bg-indigo-500",
    iconUrl: "/images/apps/6765780052/icon.jpg",
    url: "https://apps.apple.com/gb/app/captions-auto-video-subtitles/id6765780052?ct=congle-web-home&mt=8",
  },
  {
    id: "local-ai-image-generator",
    name: "Local AI Image Generator",
    category: AppCategory.UTILITIES,
    description: "Private, offline AI image generation on iPhone.",
    iconColor: "bg-blue-500",
    iconUrl: "/images/apps/6776417249/icon.jpg",
    url: "https://apps.apple.com/gb/app/local-ai-image-generator/id6776417249?ct=congle-web-home&mt=8",
  },
  {
    id: "householdvault",
    name: "HouseholdVault: ID Docs",
    category: AppCategory.UTILITIES,
    description: "A private document scanner wallet for the records your household needs when timing matters.",
    iconColor: "bg-blue-500",
    iconUrl: "/images/apps/6776387674/icon.jpg",
    url: "https://apps.apple.com/gb/app/householdvault-id-docs/id6776387674?ct=congle-web-home&mt=8",
  },
  {
    id: "pack-planner",
    name: "Pack Planner: Group Lists",
    category: AppCategory.UTILITIES,
    description: "Pack together from one shared checklist for families, friends, and travel groups.",
    iconColor: "bg-blue-500",
    iconUrl: "/images/apps/6773508857/icon.jpg",
    url: "https://apps.apple.com/gb/app/pack-planner-group-lists/id6773508857?ct=congle-web-home&mt=8",
  },
  {
    id: "tiny-table",
    name: "Tiny Table: BLW Ideas & Purees",
    category: AppCategory.UTILITIES,
    description: "Start solids with practical baby-led weaning, puree, and finger-food prep ideas.",
    iconColor: "bg-blue-500",
    iconUrl: "/images/apps/6772686797/icon.jpg",
    url: "https://apps.apple.com/gb/app/tiny-table-blw-ideas-purees/id6772686797?ct=congle-web-home&mt=8",
  },
  {
    id: "soapcraft",
    name: "SoapCraft: Soap Calculator",
    category: AppCategory.UTILITIES,
    description: "A clean soap and lye calculator for handmade soap makers.",
    iconColor: "bg-blue-500",
    iconUrl: "/images/apps/6772685450/icon.jpg",
    url: "https://apps.apple.com/gb/app/soapcraft-soap-calculator/id6772685450?ct=congle-web-home&mt=8",
  },
  {
    id: "anime-chat",
    name: "Anime Chat: Private AI",
    category: AppCategory.ENTERTAINMENT,
    description: "A private anime chat app that runs on your iPhone.",
    iconColor: "bg-purple-500",
    iconUrl: "/images/apps/6772072727/icon.jpg",
    url: "https://apps.apple.com/gb/app/anime-chat-private-ai/id6772072727?ct=congle-web-home&mt=8",
  },
  {
    id: "age-calculator",
    name: "Age Calculator: How Old Am I",
    category: AppCategory.UTILITIES,
    description: "See your exact age in years, months, and days — instantly.",
    iconColor: "bg-blue-500",
    iconUrl: "/images/apps/6770217651/icon.jpg",
    url: "https://apps.apple.com/gb/app/age-calculator-how-old-am-i/id6770217651?ct=congle-web-home&mt=8",
  },
  {
    id: "docscanner",
    name: "DocScanner: Sign Documents",
    category: AppCategory.PRODUCTIVITY,
    description: "An all-in-one document scanner that works completely offline. No account, no subscription.",
    iconColor: "bg-slate-500",
    iconUrl: "/images/apps/6769176993/icon.jpg",
    url: "https://apps.apple.com/gb/app/docscanner-sign-documents/id6769176993?ct=congle-web-home&mt=8",
  },
  {
    id: "persona-ai",
    name: "Persona AI: Story Chat",
    category: AppCategory.ENTERTAINMENT,
    description: "A private AI writing and story chat app for scenes, dialogue, and recurring characters.",
    iconColor: "bg-purple-500",
    iconUrl: "/images/apps/6768801666/icon.jpg",
    url: "https://apps.apple.com/gb/app/persona-ai-story-chat/id6768801666?ct=congle-web-home&mt=8",
  },
  {
    id: "codingchat-ai",
    name: "CodingChat AI",
    category: AppCategory.EDUCATION,
    description: "A private AI code assistant that runs on your iPhone.",
    iconColor: "bg-red-400",
    iconUrl: "/images/apps/6768466507/icon.jpg",
    url: "https://apps.apple.com/gb/app/codingchat-ai/id6768466507?ct=congle-web-home&mt=8",
  },
  {
    id: "nolo-inspiration",
    name: "NoLo Inspiration",
    category: AppCategory.UTILITIES,
    description: "Scan, discover, and rate no-alcohol and low-alcohol drinks.",
    iconColor: "bg-blue-500",
    iconUrl: "/images/apps/6761860910/icon.jpg",
    url: "https://apps.apple.com/gb/app/nolo-inspiration/id6761860910?ct=congle-web-home&mt=8",
  },
  {
    id: "cardkeeper",
    name: "CardKeeper – Wallet Passes",
    category: AppCategory.UTILITIES,
    description: "The privacy-first way to create and manage Apple Wallet passes for loyalty and membership cards.",
    iconColor: "bg-blue-500",
    iconUrl: "/images/apps/6761440158/icon.jpg",
    url: "https://apps.apple.com/gb/app/cardkeeper-wallet-passes/id6761440158?ct=congle-web-home&mt=8",
  },
  {
    id: "uv-index",
    name: "UV Index - Burn Time Tracker",
    category: AppCategory.WEATHER,
    description: "Know your personal burn time before you step outside, from clear-sky ultraviolet levels.",
    iconColor: "bg-amber-500",
    iconUrl: "/images/apps/6760960498/icon.jpg",
    url: "https://apps.apple.com/gb/app/uv-index-burn-time-tracker/id6760960498?ct=congle-web-home&mt=8",
  },
  {
    id: "moon-phases",
    name: "Moon Phases: Lunar Tracker",
    category: AppCategory.UTILITIES,
    description: "See what the moon is doing right now in under a second — no internet required.",
    iconColor: "bg-blue-500",
    iconUrl: "/images/apps/6760960352/icon.jpg",
    url: "https://apps.apple.com/gb/app/moon-phases-lunar-tracker/id6760960352?ct=congle-web-home&mt=8",
  },
  {
    id: "okaeshi",
    name: "お返し - 内祝い・香典返し管理",
    category: AppCategory.UTILITIES,
    description: "結婚・出産・香典・快気祝いなど、日本の贈答マナーに沿ったお返しの期限と金額を自動計算。",
    iconColor: "bg-blue-500",
    iconUrl: "/images/apps/6760551450/icon.jpg",
    url: "https://apps.apple.com/gb/app/%E3%81%8A%E8%BF%94%E3%81%97-%E5%86%85%E7%A5%9D%E3%81%84-%E9%A6%99%E5%85%B8%E8%BF%94%E3%81%97%E7%AE%A1%E7%90%86/id6760551450?ct=congle-web-home&mt=8",
  },
  {
    id: "baby-names",
    name: "Baby Names : Swipe & Pick",
    category: AppCategory.LIFESTYLE,
    description: "Swipe through 10,000+ baby names from 60+ cultural origins and match with your partner.",
    iconColor: "bg-pink-500",
    iconUrl: "/images/apps/6760255587/icon.jpg",
    url: "https://apps.apple.com/gb/app/baby-names-swipe-pick/id6760255587?ct=congle-web-home&mt=8",
    landingPage: "/apps/baby-names/",
  },
  {
    id: "poop-tracker",
    name: "Poop Tracker & Gut Health",
    category: AppCategory.LIFESTYLE,
    description: "Track your gut health in seconds.",
    iconColor: "bg-rose-400",
    iconUrl: "/images/apps/6760222884/icon.jpg",
    url: "https://apps.apple.com/gb/app/poop-tracker-gut-health/id6760222884?ct=congle-web-home&mt=8",
  },
  {
    id: "coloring",
    name: "Kids Coloring Book & Draw",
    category: AppCategory.EDUCATION,
    description: "Colour, draw, and create with a kids-first colouring app. Fully offline.",
    iconColor: "bg-violet-500",
    iconUrl: "/images/apps/6759912464/icon.jpg",
    url: "https://apps.apple.com/gb/app/kids-coloring-book-draw/id6759912464?ct=congle-web-home&mt=8",
    landingPage: "/apps/coloring/",
  },
  {
    id: "bible-prayer",
    name: "Bible Prayer Companion",
    category: AppCategory.EDUCATION,
    description: "A quiet, offline prayer and Scripture app built for simple daily consistency.",
    iconColor: "bg-red-400",
    iconUrl: "/images/apps/6759859294/icon.jpg",
    url: "https://apps.apple.com/gb/app/bible-prayer-companion/id6759859294?ct=congle-web-home&mt=8",
    landingPage: "/apps/bible-prayer/",
  },
  {
    id: "passport-photo",
    name: "Passport Photo: Visa & ID",
    category: AppCategory.PHOTO_VIDEO,
    description: "Create passport, visa, and ID photos that meet official government standards — processed on device.",
    iconColor: "bg-indigo-500",
    iconUrl: "/images/apps/6747094958/icon.jpg",
    url: "https://apps.apple.com/gb/app/passport-photo-visa-id/id6747094958?ct=congle-web-home&mt=8",
  },
  {
    id: "fish-finder",
    name: "Fish Finder · AI Identifier",
    category: AppCategory.LIFESTYLE,
    description: "Identify fish species with AI and keep useful details close while outdoors.",
    iconColor: "bg-cyan-600",
    iconUrl: "/images/apps/6746223793/icon.jpg",
    url: "https://apps.apple.com/gb/app/fish-finder-ai-identifier/id6746223793?ct=congle-web-home&mt=8",
    landingPage: "/apps/fish-finder/",
  },
  {
    id: "pomodoro",
    name: "Pomodoro timer: Focus",
    category: AppCategory.PRODUCTIVITY,
    description: "Simple focus sessions and breaks based on the Pomodoro method.",
    iconColor: "bg-orange-500",
    iconUrl: "/images/apps/6744445553/icon.jpg",
    url: "https://apps.apple.com/gb/app/pomodoro-timer-focus/id6744445553?ct=congle-web-home&mt=8",
  },
  {
    id: "carddex",
    name: "CardDex: TCG Scanner & Price",
    category: AppCategory.UTILITIES,
    description: "Your ultimate Pokémon card collecting companion — scan, track, and price your collection.",
    iconColor: "bg-yellow-500",
    iconUrl: "/images/apps/6743774763/icon.jpg",
    url: "https://apps.apple.com/gb/app/carddex-tcg-scanner-price/id6743774763?ct=congle-web-home&mt=8",
  },
  {
    id: "sun-times",
    name: "Sun Times: Sunrise & Sunset",
    category: AppCategory.WEATHER,
    description: "Know exactly when the sun rises and sets, to the minute, offline, anywhere on Earth.",
    iconColor: "bg-amber-500",
    iconUrl: "/images/apps/6740433779/icon.jpg",
    url: "https://apps.apple.com/gb/app/sun-times-sunrise-sunset/id6740433779?ct=congle-web-home&mt=8",
  },
  {
    id: "vidcompress",
    name: "VidCompress - Video Compressor",
    category: AppCategory.PHOTO_VIDEO,
    description: "Compress large videos quickly while keeping quality good enough to share.",
    iconColor: "bg-indigo-500",
    iconUrl: "/images/apps/6740351118/icon.jpg",
    url: "https://apps.apple.com/gb/app/vidcompress-video-compressor/id6740351118?ct=congle-web-home&mt=8",
  },
  {
    id: "photo-cleaner",
    name: "Photo Cleaner & Compressor",
    category: AppCategory.PHOTO_VIDEO,
    description: "Clean up your photo library and reclaim storage — all processed privately on your device.",
    iconColor: "bg-purple-500",
    iconUrl: "/images/apps/6740165217/icon.jpg",
    url: "https://apps.apple.com/gb/app/photo-cleaner-compressor/id6740165217?ct=congle-web-home&mt=8",
  },
  {
    id: "birthday",
    name: "Birthday Reminder & Countdowns",
    category: AppCategory.PRODUCTIVITY,
    description: "Smart birthday reminders with countdowns so important dates never slip.",
    iconColor: "bg-pink-500",
    iconUrl: "/images/apps/6739454115/icon.jpg",
    url: "https://apps.apple.com/gb/app/birthday-reminder-countdowns/id6739454115?ct=congle-web-home&mt=8",
    landingPage: "/apps/birthday-reminder/",
  },
  {
    id: "lullaby",
    name: "Lullaby Pal - White Noise",
    category: AppCategory.LIFESTYLE,
    description: "Calming white noise and ambient sounds for sleep and focus.",
    iconColor: "bg-sky-500",
    iconUrl: "/images/apps/6739187522/icon.jpg",
    url: "https://apps.apple.com/gb/app/lullaby-pal-white-noise/id6739187522?ct=congle-web-home&mt=8",
    landingPage: "/apps/lullaby-pal/",
  },
  {
    id: "baby-kicks",
    name: "Baby Kicks: Track Movements",
    category: AppCategory.LIFESTYLE,
    description: "Track baby kick sessions with simple logs and timing.",
    iconColor: "bg-pink-400",
    iconUrl: "/images/apps/6563145060/icon.jpg",
    url: "https://apps.apple.com/gb/app/baby-kicks-track-movements/id6563145060?ct=congle-web-home&mt=8",
    screenshots: [
      "/images/apps/6563145060/screenshot-1.jpg",
      "/images/apps/6563145060/screenshot-2.jpg",
      "/images/apps/6563145060/screenshot-3.jpg",
      "/images/apps/6563145060/screenshot-4.jpg",
      "/images/apps/6563145060/screenshot-5.jpg",
    ],
  },
  {
    id: "learn-japanese",
    name: "Learn Japanese",
    category: AppCategory.EDUCATION,
    description: "Build Japanese vocabulary and daily language habits with bite-sized practice.",
    iconColor: "bg-red-400",
    iconUrl: "/images/apps/1637507803/icon.jpg",
    url: "https://apps.apple.com/gb/app/learn-japanese/id1637507803?ct=congle-web-home&mt=8",
  },
  {
    id: "to-do-list",
    name: "To Do List - One focus",
    category: AppCategory.PRODUCTIVITY,
    description: "Minimal task manager focused on one thing at a time.",
    iconColor: "bg-slate-500",
    iconUrl: "/images/apps/1633843163/icon.jpg",
    url: "https://apps.apple.com/gb/app/to-do-list-one-focus/id1633843163?ct=congle-web-home&mt=8",
    screenshots: [
      "/images/apps/1633843163/screenshot-1.jpg",
      "/images/apps/1633843163/screenshot-2.jpg",
      "/images/apps/1633843163/screenshot-3.jpg",
      "/images/apps/1633843163/screenshot-4.jpg",
      "/images/apps/1633843163/screenshot-5.jpg",
    ],
  },
  {
    id: "othello",
    name: "Othello - TEAMCONG",
    category: AppCategory.ENTERTAINMENT,
    description: "Classic strategy board game implementation.",
    iconColor: "bg-neutral-600",
    iconUrl: "/images/apps/1590705319/icon.jpg",
    url: "https://apps.apple.com/gb/app/othello-teamcong/id1590705319?ct=congle-web-home&mt=8",
    screenshots: [
      "/images/apps/1590705319/screenshot-1.jpg",
      "/images/apps/1590705319/screenshot-2.jpg",
      "/images/apps/1590705319/screenshot-3.jpg",
    ],
  },
  {
    id: "run-run-run",
    name: "Run Run Run",
    category: AppCategory.ENTERTAINMENT,
    description: "Arcade runner game with fast-paced gameplay.",
    iconColor: "bg-orange-500",
    iconUrl: "/images/apps/1582701318/icon.jpg",
    url: "https://apps.apple.com/gb/app/run-run-run/id1582701318?ct=congle-web-home&mt=8",
    screenshots: [
      "/images/apps/1582701318/screenshot-1.jpg",
      "/images/apps/1582701318/screenshot-2.jpg",
      "/images/apps/1582701318/screenshot-3.jpg",
      "/images/apps/1582701318/screenshot-4.jpg",
    ],
  },
  {
    id: "solitaire",
    name: "Solitaire - TEAMCONG",
    category: AppCategory.ENTERTAINMENT,
    description: "Classic solitaire card game for quick sessions.",
    iconColor: "bg-emerald-600",
    iconUrl: "/images/apps/1582328906/icon.jpg",
    url: "https://apps.apple.com/gb/app/solitaire-teamcong/id1582328906?ct=congle-web-home&mt=8",
    screenshots: [
      "/images/apps/1582328906/screenshot-1.jpg",
      "/images/apps/1582328906/screenshot-2.jpg",
      "/images/apps/1582328906/screenshot-3.jpg",
    ],
  },
  {
    id: "fish-run",
    name: "Fish Run - Collect stars",
    category: AppCategory.ENTERTAINMENT,
    description: "Casual game: collect stars and avoid obstacles.",
    iconColor: "bg-cyan-500",
    iconUrl: "/images/apps/1580103922/icon.jpg",
    url: "https://apps.apple.com/gb/app/fish-run-collect-stars/id1580103922?ct=congle-web-home&mt=8",
    screenshots: [
      "/images/apps/1580103922/screenshot-1.jpg",
      "/images/apps/1580103922/screenshot-2.jpg",
      "/images/apps/1580103922/screenshot-3.jpg",
      "/images/apps/1580103922/screenshot-4.jpg",
    ],
  },
  {
    id: "water-plants",
    name: "Water them plants",
    category: AppCategory.LIFESTYLE,
    description: "Plant care reminders and watering schedules.",
    iconColor: "bg-green-500",
    iconUrl: "/images/apps/1573313539/icon.jpg",
    url: "https://apps.apple.com/gb/app/water-them-plants/id1573313539?ct=congle-web-home&mt=8",
    screenshots: [
      "/images/apps/1573313539/screenshot-1.jpg",
      "/images/apps/1573313539/screenshot-2.jpg",
      "/images/apps/1573313539/screenshot-3.jpg",
    ],
  },
];
